AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  battleships

Globals:
  Function:
    Timeout: 3

Resources:
  CreateGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: server/create_game
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /game
            Method: POST
  GetGamesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: server/get_games
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /game
            Method: GET
  GetGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: server/get_game
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /game/{id}/{player_id}
            Method: GET
  PerformActionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: server/perform_action
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /game/{id}/{player_id}
            Method: POST

Outputs:
  BattleshipsApi:
    Description: "API Gateway URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
