AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  battleships

Globals:
  Function:
    Timeout: 3

Resources:
  BattleshipsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: battleships-table
      SSESpecification:
        SSEEnabled: true
  CreateGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: server/create_game
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        CreateGame:
          Type: Api
          Properties:
            Path: /game
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BattleshipsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref BattleshipsTable
  GetGamesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: server/get_games
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        GetGames:
          Type: Api
          Properties:
            Path: /game
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BattleshipsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref BattleshipsTable
  GetGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: server/get_game
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        GetGame:
          Type: Api
          Properties:
            Path: /game/{id}/{player_id}
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BattleshipsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref BattleshipsTable
  PerformActionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: server/perform_action
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        PerformAction:
          Type: Api
          Properties:
            Path: /game/{id}/{player_id}
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BattleshipsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref BattleshipsTable

Outputs:
  BattleshipsApi:
    Description: "API Gateway URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
